apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  - image: superclass2016/multi-client
    context: ./client
    sync:
      manual:
      - src: '**/*.js'
        dest: .
      - src: '**/*.css'
        dest: .
      - src: '**/*.html'
        dest: .
    docker:
      dockerfile: Dockerfile.dev
  local:
    push: false
deploy:
  kubectl:
    manifests:
    - k8s/client-deployment.yaml
